import type { NextPage } from 'next'
import Head from 'next/head'
import {Header, Navbar, About, Projects, Contact} from "../components";

const Home: NextPage = () => {
  return (
    <div >
      <Head>
        <title>Sebastien&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/icon-512x512.png" />
        <link rel="manifest" href="/manifest.json" />
        <link rel="apple-touch-icon" href="/icon-512x512.png" />
        <meta name="theme-color" content="#222" />
        <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css" />
        <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Raleway" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" />
      </Head>

      <main>
          <Navbar />
          <Header />
          <About />
          <Projects />
          <Contact />
      </main>
    </div>
  )
}

export default Home
